name: Build and deploy Jekyll site

on:
  schedule:
    - cron:  '0 12 * * *'  # Runs every day at 12:00 UTC

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Jekyll site
      uses: jekyll/builder@main
      with:
        args: jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
